### ISSUE TITLE
Add userId to filter expressions 

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy-addon#40]
According to [the spec](http://normandy.readthedocs.io/en/latest/user/filter_expressions.html#normandy.userId), filter expressions should have access to `normandy.userId`, which is a persistent UUID unrelated to any other unique ID, such as the Telemetry ID.

**Comment by Osmose** [comment]
Moved to the monorepo: https://github.com/mozilla/normandy/issues/414
